### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by broadsw0rd** [broadsw0rd/chart#2]
- [x] Sepparate files
- [x] ~~Point class~~
- [x] Colors
- [x] `Chart#clear` by `clearRect`
- [x] Few charts in demo
- [x] Dark background
- [x] [Turn off antialiasing](http://stackoverflow.com/questions/195262/can-i-turn-off-antialiasing-on-an-html-canvas-element). [Clear](http://stackoverflow.com/questions/5526486/clear-entire-transformed-html5-canvas-while-preserving-context-transform)
- [x] fix `Not optimized: Optimized too many times` DevTools warning
